In [1]:
'''
Você tem uma lista de número: [6,7,4,7,8,4,2,5,7,'hum', 'dois']. A ideia do exercício é
tirar a média de todos os valores contidos na lista, porém para fazer o cálculo
precisa remover as strings
'''

lista = [6,7,4,7,8,4,2,5,7,'hum', 'dois']
cont = 0
qtd = 0
for x in lista:
    qtd += 1
    #verifica se o elemento e um numero
    if isinstance(x,int) == True:
        cont += x
print(qtd)
print(cont)
print('Média dos números da lista é = {:.2f}'.format(cont/qtd))



11
50
Média dos números da lista é = 4.55


In [2]:
'''
Crie um método que receba duas matrizes, some os valores total de cada matriz e
depois multiple o resultado delas e retorne o valor.
'''
def matrizes(mat1, mat2):
    cont1 = 0
    cont2 = 0
    #somando valores da matriz 2
    for linha in mat1:
        for coluna in linha:
            cont1 += coluna
    #somando valores da matriz 2
    for linha in mat2:
        for coluna in linha:
            cont2 += coluna
    #multiplicando resultado da soma das matrizes
    print(cont1 * cont2)


lista1 = [[1, 2], [3, 4], [5, 6]]
lista2 = [[7, 8], [9, 10], [11, 12]]
matrizes(lista1, lista2)


1197


In [3]:
'''
Criar uma matriz nxm (n = 5, m =7)
'''
import numpy as np
matriz = np.array(np.arange(35))
matriz.shape = (5,7)
print(matriz)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [4]:
#faça a matriz transposta desta matriz

import numpy as np
#comando arange é para gerar um lista com 35 numeros e o comando array transforma essa lista em um array
matriz = np.array(np.arange(35))
#comando shape transforma meu array em uma matriz
matriz.shape = (5,7)
transposta = matriz.transpose()
print(transposta)

[[ 0  7 14 21 28]
 [ 1  8 15 22 29]
 [ 2  9 16 23 30]
 [ 3 10 17 24 31]
 [ 4 11 18 25 32]
 [ 5 12 19 26 33]
 [ 6 13 20 27 34]]


In [5]:
#somar toda matrix
import numpy as np
matriz = np.array(np.arange(35))
matriz.shape = (5,7)
print(matriz)
matriz.sum()

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


595

In [6]:
#somar todas as colunas
import numpy as np
matriz = np.array(np.arange(35))
matriz.shape = (5,7)
#axis = 0 se refere a coluna
matriz.sum(axis=0)

array([ 70,  75,  80,  85,  90,  95, 100])

In [7]:
#somar todas as linhas.
import numpy as np
matriz = np.array(np.arange(35))
matriz.shape = (5,7)
#axis = 1 se refere a linha
matriz.sum(axis=1)	

array([ 21,  70, 119, 168, 217])

In [8]:
#retorne o maior valor
import numpy as np
matriz = np.array(np.arange(35))
matriz.shape = (5,7)
maior = 0
for i in matriz:
  for j in i:
  	#comparacao para obter o maior numero
    if j >= maior:
      maior = j
#usando numpy para obter o maior numero
maior1 = matriz.max()
print('Maior numero da matriz usando for: {}'.format(maior))
print('Maior numero da matriz usando numpy: {}'.format(maior1))

Maior numero da matriz usando for: 34
Maior numero da matriz usando numpy: 34


In [9]:
#retorne o menor valor.
import numpy as np
matriz = np.array(np.arange(35))
matriz.shape = (5,7)
menor = matriz.min()
print(menor)

0


In [12]:
#Crie uma matriz nxn (n=5). Agora some essa matriz com a matriz do exercício 3.
import numpy as np
matriz = np.array(np.arange(35))
matriz.shape = (5,7)
matriz2 = np.array(np.arange(25))
matriz2.shape= (5,5)
soma = matriz.sum() + matriz2.sum()
print(soma)

895


In [13]:
#crie um array de números que vai de 0 a 1000.
import numpy as np
np.arange(1001)

array([   0,    1,    2, ...,  998,  999, 1000])

In [ ]:
#crie uma matriz só de zeros.
import numpy as np
np.zeros((5,5))